-- サンプルデータ：詳細仕様付きプレス機
-- 既存データと統合するため、id, org_id, machine_numberなどを含む完全形

-- KOMATSU H1F200-11 (機械番号: 010)
insert into public.press_machines (
  org_id, machine_number, equipment_number,
  manufacturer, model_type, machine_type, production_group,
  maker, model, serial_no, manufacture_year, manufacture_month,
  capacity_kn, capacity_ton, stroke_spm_min, stroke_spm_max, stroke_length_mm,
  die_height_mm, slide_adjust_mm,
  slide_size_lr_mm, slide_size_fb_mm,
  bolster_size_lr_mm, bolster_size_fb_mm, bolster_thickness_mm,
  max_down_speed_mm_s,
  stop_time_emergency_ms, inertia_drop_mm,
  max_upper_die_weight_kg,
  ambient_temp_min_c, ambient_temp_max_c,
  notes
) values (
  '550e8400-e29b-41d4-a716-446655440000'::uuid, '010', '25',
  'KOMATSU', 'H1F200-11', '圧造', 1,
  'KOMATSU','H1F200-11','10125',2007,8,
  2000, null, 35, 35, 250,
  520, 120,
  850, 720,
  1200, 840, 190,
  382,
  200, 35,
  650,
  5, 40,
  'スライド寸法/ボルスタ寸法は銘板表記。'
) on conflict (org_id, machine_number) do update set
  manufacturer = excluded.manufacturer,
  model_type = excluded.model_type,
  maker = excluded.maker,
  model = excluded.model,
  serial_no = excluded.serial_no,
  manufacture_year = excluded.manufacture_year,
  manufacture_month = excluded.manufacture_month,
  capacity_kn = excluded.capacity_kn,
  stroke_spm_min = excluded.stroke_spm_min,
  stroke_spm_max = excluded.stroke_spm_max,
  stroke_length_mm = excluded.stroke_length_mm,
  die_height_mm = excluded.die_height_mm,
  slide_adjust_mm = excluded.slide_adjust_mm,
  slide_size_lr_mm = excluded.slide_size_lr_mm,
  slide_size_fb_mm = excluded.slide_size_fb_mm,
  bolster_size_lr_mm = excluded.bolster_size_lr_mm,
  bolster_size_fb_mm = excluded.bolster_size_fb_mm,
  bolster_thickness_mm = excluded.bolster_thickness_mm,
  max_down_speed_mm_s = excluded.max_down_speed_mm_s,
  stop_time_emergency_ms = excluded.stop_time_emergency_ms,
  inertia_drop_mm = excluded.inertia_drop_mm,
  max_upper_die_weight_kg = excluded.max_upper_die_weight_kg,
  ambient_temp_min_c = excluded.ambient_temp_min_c,
  ambient_temp_max_c = excluded.ambient_temp_max_c,
  notes = excluded.notes;

-- AMADA TPL80SI (機械番号: 018)
insert into public.press_machines (
  org_id, machine_number, equipment_number,
  manufacturer, model_type, machine_type, production_group, tonnage,
  maker, model, serial_no, manufacture_year, manufacture_month,
  capacity_kn, capacity_ton, stroke_spm_min, stroke_spm_max, stroke_length_mm,
  die_height_mm, slide_adjust_mm,
  slide_size_lr_mm, slide_size_fb_mm,
  bolster_size_lr_mm, bolster_size_fb_mm,
  stop_time_emergency_ms,
  motor_power_kw, power_spec_text, air_pressure_kgf_cm2,
  overrun_angle_min_deg, overrun_angle_max_deg,
  notes
) values (
  '550e8400-e29b-41d4-a716-446655440000'::uuid, '018', '30',
  'AMADA', 'TPL80SI', '汎用', 2, 80,
  'AMADA','TPL80SI','02410101',1999,1,
  null, 80, 50, 95, 130,
  320, 80,
  550, 450,
  1030, 600,
  200,
  7.5, '200V 3相 60Hz', 5.0,
  15, 15,
  'ボルスタ厚みの表記なし。'
) on conflict (org_id, machine_number) do update set
  manufacturer = excluded.manufacturer,
  model_type = excluded.model_type,
  tonnage = excluded.tonnage,
  maker = excluded.maker,
  model = excluded.model,
  serial_no = excluded.serial_no,
  manufacture_year = excluded.manufacture_year,
  manufacture_month = excluded.manufacture_month,
  capacity_ton = excluded.capacity_ton,
  stroke_spm_min = excluded.stroke_spm_min,
  stroke_spm_max = excluded.stroke_spm_max,
  stroke_length_mm = excluded.stroke_length_mm,
  die_height_mm = excluded.die_height_mm,
  slide_adjust_mm = excluded.slide_adjust_mm,
  slide_size_lr_mm = excluded.slide_size_lr_mm,
  slide_size_fb_mm = excluded.slide_size_fb_mm,
  bolster_size_lr_mm = excluded.bolster_size_lr_mm,
  bolster_size_fb_mm = excluded.bolster_size_fb_mm,
  stop_time_emergency_ms = excluded.stop_time_emergency_ms,
  motor_power_kw = excluded.motor_power_kw,
  power_spec_text = excluded.power_spec_text,
  air_pressure_kgf_cm2 = excluded.air_pressure_kgf_cm2,
  overrun_angle_min_deg = excluded.overrun_angle_min_deg,
  overrun_angle_max_deg = excluded.overrun_angle_max_deg,
  notes = excluded.notes;

-- AIDA K1-2500 (機械番号: 002)
insert into public.press_machines (
  org_id, machine_number, equipment_number,
  manufacturer, model_type, machine_type, production_group,
  maker, model, serial_no, manufacture_year, manufacture_month,
  capacity_kn, capacity_ton, stroke_spm_min, stroke_spm_max, stroke_length_mm,
  die_height_mm, slide_adjust_mm,
  slide_size_lr_mm, slide_size_fb_mm,
  bolster_size_lr_mm, bolster_size_fb_mm,
  stop_time_emergency_ms, stop_time_twohand_ms, stop_time_light_ms,
  max_upper_die_weight_kg,
  motor_power_kw, air_pressure_mpa,
  overrun_angle_min_deg, overrun_angle_max_deg,
  notes
) values (
  '550e8400-e29b-41d4-a716-446655440000'::uuid, '002', '15',
  'AIDA', 'K1-2500', '圧造', 1,
  'AIDA','K1-2500','10302-1230',2001,3,
  2500, null, 30, 60, 160,
  400, 50,
  600, 400,
  600, 500,
  185, 185, 205,
  400,
  30, 0.5,
  9, 15,
  'オーバーラン監視装置設定位置 12°±3°を9〜15°に換算。'
) on conflict (org_id, machine_number) do update set
  manufacturer = excluded.manufacturer,
  model_type = excluded.model_type,
  maker = excluded.maker,
  model = excluded.model,
  serial_no = excluded.serial_no,
  manufacture_year = excluded.manufacture_year,
  manufacture_month = excluded.manufacture_month,
  capacity_kn = excluded.capacity_kn,
  stroke_spm_min = excluded.stroke_spm_min,
  stroke_spm_max = excluded.stroke_spm_max,
  stroke_length_mm = excluded.stroke_length_mm,
  die_height_mm = excluded.die_height_mm,
  slide_adjust_mm = excluded.slide_adjust_mm,
  slide_size_lr_mm = excluded.slide_size_lr_mm,
  slide_size_fb_mm = excluded.slide_size_fb_mm,
  bolster_size_lr_mm = excluded.bolster_size_lr_mm,
  bolster_size_fb_mm = excluded.bolster_size_fb_mm,
  stop_time_emergency_ms = excluded.stop_time_emergency_ms,
  stop_time_twohand_ms = excluded.stop_time_twohand_ms,
  stop_time_light_ms = excluded.stop_time_light_ms,
  max_upper_die_weight_kg = excluded.max_upper_die_weight_kg,
  motor_power_kw = excluded.motor_power_kw,
  air_pressure_mpa = excluded.air_pressure_mpa,
  overrun_angle_min_deg = excluded.overrun_angle_min_deg,
  overrun_angle_max_deg = excluded.overrun_angle_max_deg,
  notes = excluded.notes;